--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/6/2022 12:00:48 AM
-- Server version: 8.0.27
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE da6;

--
-- Drop table `aos`
--
DROP TABLE IF EXISTS aos;

--
-- Drop table `chungloais`
--
DROP TABLE IF EXISTS chungloais;

--
-- Drop table `daiquans`
--
DROP TABLE IF EXISTS daiquans;

--
-- Drop table `dauras`
--
DROP TABLE IF EXISTS dauras;

--
-- Drop table `files`
--
DROP TABLE IF EXISTS files;

--
-- Drop table `jackets`
--
DROP TABLE IF EXISTS jackets;

--
-- Drop table `kieucaps`
--
DROP TABLE IF EXISTS kieucaps;

--
-- Drop table `kieucos`
--
DROP TABLE IF EXISTS kieucos;

--
-- Drop table `kieucuaquans`
--
DROP TABLE IF EXISTS kieucuaquans;

--
-- Drop table `kieucuatays`
--
DROP TABLE IF EXISTS kieucuatays;

--
-- Drop table `kieugaus`
--
DROP TABLE IF EXISTS kieugaus;

--
-- Drop table `kieuneps`
--
DROP TABLE IF EXISTS kieuneps;

--
-- Drop table `kieuquans`
--
DROP TABLE IF EXISTS kieuquans;

--
-- Drop table `kieutays`
--
DROP TABLE IF EXISTS kieutays;

--
-- Drop table `kieuthansaus`
--
DROP TABLE IF EXISTS kieuthansaus;

--
-- Drop table `kieuthantruocs`
--
DROP TABLE IF EXISTS kieuthantruocs;

--
-- Drop table `kieutuigois`
--
DROP TABLE IF EXISTS kieutuigois;

--
-- Drop table `kieutuis`
--
DROP TABLE IF EXISTS kieutuis;

--
-- Drop table `kieutuisaus`
--
DROP TABLE IF EXISTS kieutuisaus;

--
-- Drop table `kieutuitruocs`
--
DROP TABLE IF EXISTS kieutuitruocs;

--
-- Drop table `kieuxes`
--
DROP TABLE IF EXISTS kieuxes;

--
-- Drop table `loaidauras`
--
DROP TABLE IF EXISTS loaidauras;

--
-- Drop table `loaitrangphucs`
--
DROP TABLE IF EXISTS loaitrangphucs;

--
-- Drop table `loaivais`
--
DROP TABLE IF EXISTS loaivais;

--
-- Drop table `nguoidungs`
--
DROP TABLE IF EXISTS nguoidungs;

--
-- Drop table `optionaos`
--
DROP TABLE IF EXISTS optionaos;

--
-- Drop table `optiondauras`
--
DROP TABLE IF EXISTS optiondauras;

--
-- Drop table `phuthuocs`
--
DROP TABLE IF EXISTS phuthuocs;

--
-- Drop table `quans`
--
DROP TABLE IF EXISTS quans;

--
-- Drop table `quytrinhchitiets`
--
DROP TABLE IF EXISTS quytrinhchitiets;

--
-- Drop table `quytrinhsanphams`
--
DROP TABLE IF EXISTS quytrinhsanphams;

--
-- Drop table `thanhphanvais`
--
DROP TABLE IF EXISTS thanhphanvais;

--
-- Drop table `vets`
--
DROP TABLE IF EXISTS vets;

--
-- Drop table `__efmigrationshistory`
--
DROP TABLE IF EXISTS __efmigrationshistory;

--
-- Set default database
--
USE da6;

--
-- Create table `__efmigrationshistory`
--
CREATE TABLE __efmigrationshistory (
  MigrationId varchar(150) NOT NULL,
  ProductVersion varchar(32) NOT NULL,
  PRIMARY KEY (MigrationId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `vets`
--
CREATE TABLE vets (
  MaVest varchar(255) NOT NULL,
  MaCL longtext NOT NULL,
  KieuNep longtext NOT NULL,
  KieuVe longtext NOT NULL,
  KieuCo longtext NOT NULL,
  KieuTuiNguc longtext NOT NULL,
  KieuTuiSuon longtext NOT NULL,
  KieuTay longtext NOT NULL,
  KieuThanTruoc longtext NOT NULL,
  KieuThanSau longtext NOT NULL,
  DaiAo float NOT NULL,
  VongGau float NOT NULL,
  VongNguc float NOT NULL,
  DaiTay float NOT NULL,
  ThanhPhanVai1 longtext NOT NULL,
  KhoVai1 float NOT NULL,
  ThanhPhanVai2 longtext NOT NULL,
  KhoVai2 float NOT NULL,
  ThanhPhanVai3 longtext NOT NULL,
  KhoVai3 float NOT NULL,
  ThanhPhanVaiLot1 longtext NOT NULL,
  KhoVaiLot1 float NOT NULL,
  ThanhPhanVaiLot2 longtext NOT NULL,
  KhoVaiLot2 float NOT NULL,
  ThanhPhanVaiLot3 longtext NOT NULL,
  KhoVaiLot3 float NOT NULL,
  SoSanPhanTrenSoDo int NOT NULL,
  SoLaoDongTrenDayTruyen int NOT NULL,
  MucLuongKyVong float NOT NULL,
  LoiNhuanDuKien float NOT NULL,
  PhuPhi float NOT NULL,
  KhoanPhiKhac float NOT NULL,
  PRIMARY KEY (MaVest)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `thanhphanvais`
--
CREATE TABLE thanhphanvais (
  MaThanhPhanVai int NOT NULL AUTO_INCREMENT,
  TenThanhPhanVai longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaThanhPhanVai)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `quytrinhsanphams`
--
CREATE TABLE quytrinhsanphams (
  MaQuyTrinhSanPham varchar(255) NOT NULL,
  STT int NOT NULL,
  MaSanPham longtext NOT NULL,
  TenQuyTrinh longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaQuyTrinhSanPham)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `quytrinhchitiets`
--
CREATE TABLE quytrinhchitiets (
  MaQuyTrinhChiTiet varchar(255) NOT NULL,
  STT int NOT NULL,
  NoiDungBuoc longtext NOT NULL,
  ThietBi longtext NOT NULL,
  BacTho longtext NOT NULL,
  ThoiGianCheTao int NOT NULL,
  DonGia float NOT NULL,
  GhiChu longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaQuyTrinhChiTiet)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `quans`
--
CREATE TABLE quans (
  MaQuan varchar(255) NOT NULL,
  MaCL longtext NOT NULL,
  KieuQuan longtext NOT NULL,
  KieuCap longtext NOT NULL,
  KieuTuiTruoc longtext NOT NULL,
  KieuTuiSau longtext NOT NULL,
  KieuTuiGoi longtext NOT NULL,
  KieuCuaQuan longtext NOT NULL,
  KieuThanTruoc longtext NOT NULL,
  KieuThanSau longtext NOT NULL,
  DaiQuan longtext NOT NULL,
  VongMong float NOT NULL,
  VongBung float NOT NULL,
  ThanhPhanVai1 longtext NOT NULL,
  KhoVai1 float NOT NULL,
  ThanhPhanVai2 longtext NOT NULL,
  KhoVai2 float NOT NULL,
  ThanhPhanVai3 longtext NOT NULL,
  KhoVai3 float NOT NULL,
  ThanhPhanVaiLot1 longtext NOT NULL,
  KhoVaiLot1 float NOT NULL,
  ThanhPhanVaiLot2 longtext NOT NULL,
  KhoVaiLot2 float NOT NULL,
  ThanhPhanVaiLot3 longtext NOT NULL,
  KhoVaiLot3 float NOT NULL,
  SoSanPhanTrenSoDo int NOT NULL,
  SoLaoDongTrenDayTruyen int NOT NULL,
  MucLuongKyVong float NOT NULL,
  LoiNhuanDuKien float NOT NULL,
  PhuPhi float NOT NULL,
  KhoanPhiKhac float NOT NULL,
  PRIMARY KEY (MaQuan)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `phuthuocs`
--
CREATE TABLE phuthuocs (
  Id int NOT NULL AUTO_INCREMENT,
  MaDauRa int NOT NULL DEFAULT 0,
  MaLoaiDauRa int NOT NULL DEFAULT 0,
  MaOptionDaura int NOT NULL DEFAULT 0,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 25,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `optiondauras`
--
CREATE TABLE optiondauras (
  Id int NOT NULL AUTO_INCREMENT,
  Name longtext NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 25,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `optionaos`
--
CREATE TABLE optionaos (
  Id int NOT NULL AUTO_INCREMENT,
  MaAo longtext NOT NULL,
  MaKieuTay int NOT NULL,
  MaKieuCuaTay int NOT NULL,
  MaKieuGau int NOT NULL,
  MaKieuCo int NOT NULL,
  MaKieuTui int NOT NULL,
  MaKieuNep int NOT NULL,
  MaKieuThanTruoc int NOT NULL,
  MaKieuXe int NOT NULL,
  MaKieuThanSau int NOT NULL,
  MaThanhPhanVai1 int NOT NULL,
  MaThanhPhanVai2 int NOT NULL,
  MaThanhPhanVai3 int NOT NULL,
  MaCL longtext NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `nguoidungs`
--
CREATE TABLE nguoidungs (
  NguoiDungId char(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  TenNguoiDung longtext NOT NULL,
  TaiKhoan longtext NOT NULL,
  MatKhau longtext NOT NULL,
  Email longtext NOT NULL,
  SoDienThoai longtext NOT NULL,
  Quyen longtext NOT NULL,
  PRIMARY KEY (NguoiDungId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `loaivais`
--
CREATE TABLE loaivais (
  MaVai varchar(255) NOT NULL,
  TenVai longtext DEFAULT NULL,
  ThanhPhan longtext NOT NULL,
  ChucNang longtext NOT NULL,
  MoTa longtext NOT NULL,
  PRIMARY KEY (MaVai)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `loaitrangphucs`
--
CREATE TABLE loaitrangphucs (
  MaTP varchar(255) NOT NULL,
  Ten varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  MoTa varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaTP)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `loaidauras`
--
CREATE TABLE loaidauras (
  Id int NOT NULL AUTO_INCREMENT,
  Name longtext NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieuxes`
--
CREATE TABLE kieuxes (
  MaKieuXe int NOT NULL AUTO_INCREMENT,
  TenKieuXe longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuXe)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieutuitruocs`
--
CREATE TABLE kieutuitruocs (
  MaKieuTuiTruoc int NOT NULL AUTO_INCREMENT,
  TenKieuTuiTruoc longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuTuiTruoc)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieutuisaus`
--
CREATE TABLE kieutuisaus (
  MaKieuTuiSau int NOT NULL AUTO_INCREMENT,
  TenKieuTuiSau longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuTuiSau)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieutuis`
--
CREATE TABLE kieutuis (
  MaKieuTui int NOT NULL AUTO_INCREMENT,
  TenKieuTui longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuTui)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieutuigois`
--
CREATE TABLE kieutuigois (
  MaKieuTuiGoi int NOT NULL AUTO_INCREMENT,
  TenKieuTuiGoi longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuTuiGoi)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieuthantruocs`
--
CREATE TABLE kieuthantruocs (
  MaKieuThanTruoc int NOT NULL AUTO_INCREMENT,
  TenKieuThanTruoc longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuThanTruoc)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieuthansaus`
--
CREATE TABLE kieuthansaus (
  MaKieuThanSau int NOT NULL AUTO_INCREMENT,
  TenKieuThanSau longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuThanSau)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieutays`
--
CREATE TABLE kieutays (
  MaKieuTay int NOT NULL AUTO_INCREMENT,
  TenKieu longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuTay)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieuquans`
--
CREATE TABLE kieuquans (
  MaKieuQuan int NOT NULL AUTO_INCREMENT,
  TenKieuQuan longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuQuan)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieuneps`
--
CREATE TABLE kieuneps (
  MaKieuNep int NOT NULL AUTO_INCREMENT,
  TenKieuNep longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuNep)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieugaus`
--
CREATE TABLE kieugaus (
  MaKieuGau int NOT NULL AUTO_INCREMENT,
  TenKieuGau longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuGau)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieucuatays`
--
CREATE TABLE kieucuatays (
  MaKieuCuaTay int NOT NULL AUTO_INCREMENT,
  TenKieuCuaTay longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuCuaTay)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieucuaquans`
--
CREATE TABLE kieucuaquans (
  MaKieuCuaQuan int NOT NULL AUTO_INCREMENT,
  TenKieuCuaQuan longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuCuaQuan)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieucos`
--
CREATE TABLE kieucos (
  MaKieuCo int NOT NULL AUTO_INCREMENT,
  TenKieuCo longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuCo)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieucaps`
--
CREATE TABLE kieucaps (
  MaKieuCap int NOT NULL AUTO_INCREMENT,
  TenKieuCap longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaKieuCap)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `jackets`
--
CREATE TABLE jackets (
  MaJket varchar(255) NOT NULL,
  MaCL longtext NOT NULL,
  Ruot longtext NOT NULL,
  KieuChan longtext NOT NULL,
  KieuGau longtext NOT NULL,
  KieuMu longtext NOT NULL,
  KieuCo longtext NOT NULL,
  KieuTuiNguc longtext NOT NULL,
  KieuTuiSuon longtext NOT NULL,
  KieuKhoaNep longtext NOT NULL,
  KieuTay longtext NOT NULL,
  KieuThanTruoc longtext NOT NULL,
  DaiAo float NOT NULL,
  VongNguc float NOT NULL,
  DaiTay float NOT NULL,
  ThanhPhanVaiChinh1 longtext NOT NULL,
  KhoVaiChinh1 float NOT NULL,
  ThanhPhanVaiChinh2 longtext NOT NULL,
  KhoVaiChinh2 float NOT NULL,
  ThanhPhanVaiChinh3 longtext NOT NULL,
  KhoVaiChinh3 float NOT NULL,
  ThanhPhanVaiLot1 longtext NOT NULL,
  KhoVaiLot1 float NOT NULL,
  ThanhPhanVaiLot2 longtext NOT NULL,
  KhoVaiLot2 float NOT NULL,
  ThanhPhanVaiLot3 longtext NOT NULL,
  KhoVaiLot3 float NOT NULL,
  SoSanPhanTrenSoDo int NOT NULL,
  SoLaoDongTrenDayTruyen int NOT NULL,
  MucLuongKyVong float NOT NULL,
  LoiNhuanDuKien float NOT NULL,
  PhuPhi float NOT NULL,
  KhoanPhiKhac float NOT NULL,
  PRIMARY KEY (MaJket)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `files`
--
CREATE TABLE files (
  MaFile int NOT NULL AUTO_INCREMENT,
  TenFile longtext NOT NULL,
  Path longtext NOT NULL,
  Size longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaFile)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `dauras`
--
CREATE TABLE dauras (
  Id int NOT NULL AUTO_INCREMENT,
  Name longtext NOT NULL,
  PRIMARY KEY (Id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 26,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `daiquans`
--
CREATE TABLE daiquans (
  MaDaiQuan int NOT NULL AUTO_INCREMENT,
  TenDaiQuan longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaDaiQuan)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `chungloais`
--
CREATE TABLE chungloais (
  MaCL varchar(255) NOT NULL,
  Ten longtext DEFAULT NULL,
  MoTa longtext DEFAULT NULL,
  Kieu longtext DEFAULT NULL,
  ParenId varchar(255) DEFAULT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  Level int NOT NULL DEFAULT 0,
  PRIMARY KEY (MaCL)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 528,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `aos`
--
CREATE TABLE aos (
  MaA varchar(255) NOT NULL,
  MaCL longtext NOT NULL,
  KieuTay longtext NOT NULL,
  KieuCuaTay longtext NOT NULL,
  KieuGau longtext NOT NULL,
  KieuCo longtext NOT NULL,
  KieuTui longtext NOT NULL,
  KieuNep longtext NOT NULL,
  KieuThanTruoc longtext NOT NULL,
  KieuXe longtext NOT NULL,
  KieuThanSau longtext NOT NULL,
  DaiAo float NOT NULL,
  DaiTay float NOT NULL,
  VongNguc float NOT NULL,
  VongMong float NOT NULL,
  ThanhPhanVai1 longtext NOT NULL,
  TrongLuongVai1 float NOT NULL,
  KhoVai1 float NOT NULL,
  ThanhPhanVai2 longtext NOT NULL,
  TrongLuongVai2 float NOT NULL,
  KhoVai2 float NOT NULL,
  ThanhPhanVai3 longtext NOT NULL,
  TrongLuongVai3 float NOT NULL,
  KhoVai3 float NOT NULL,
  SoSanPhanTrenSoDo int NOT NULL,
  SoLaoDongTrenDayTruyen int NOT NULL,
  MucLuongKyVong float NOT NULL,
  LoiNhuanDuKien float NOT NULL,
  PhuPhi float NOT NULL,
  KhoanPhiKhac float NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) DEFAULT NULL,
  PRIMARY KEY (MaA)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table __efmigrationshistory
--
INSERT INTO __efmigrationshistory VALUES
('20220521102804_initial', '6.0.4'),
('20220522033611_AddFile', '6.0.4'),
('20220522043935_addbaseClassfile', '6.0.4'),
('20220522072212_updatetableNguoidung', '6.0.4'),
('20220522163016_addlevelForTableChungLoai', '6.0.4'),
('20220524153003_AddTableOptionAo', '6.0.4'),
('20220602131956_addTableTieuChuanDauRa', '6.0.4'),
('20220602151922_addTable', '6.0.4'),
('20220602153202_updatetabledaura', '6.0.4'),
('20220604003042_updateTable', '6.0.4'),
('20220604165038_updatetableNew', '6.0.4');

-- 
-- Dumping data for table vets
--
-- Table da6.vets does not contain any data (it is empty)

-- 
-- Dumping data for table thanhphanvais
--
INSERT INTO thanhphanvais VALUES
(1, 'bông 100%', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'TC 65-35', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'TC 35-65', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(4, 'PES 100%', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(5, 'Ryon', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(6, 'Bambo', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table quytrinhsanphams
--
-- Table da6.quytrinhsanphams does not contain any data (it is empty)

-- 
-- Dumping data for table quytrinhchitiets
--
-- Table da6.quytrinhchitiets does not contain any data (it is empty)

-- 
-- Dumping data for table quans
--
-- Table da6.quans does not contain any data (it is empty)

-- 
-- Dumping data for table phuthuocs
--
INSERT INTO phuthuocs VALUES
(1, 0, 0, 0),
(2, 0, 0, 0),
(3, 0, 0, 0),
(4, 0, 0, 0),
(5, 0, 0, 0),
(6, 0, 0, 0),
(7, 0, 0, 0),
(8, 0, 0, 0),
(9, 0, 0, 0),
(10, 0, 0, 0),
(11, 0, 0, 0),
(12, 0, 0, 0),
(13, 0, 0, 0),
(14, 0, 0, 0),
(15, 0, 0, 0),
(16, 0, 0, 0),
(17, 0, 0, 0),
(18, 0, 0, 0),
(19, 0, 0, 0),
(20, 0, 0, 0),
(21, 0, 0, 0),
(22, 0, 0, 0),
(23, 0, 0, 0),
(24, 0, 0, 0);

-- 
-- Dumping data for table optiondauras
--
INSERT INTO optiondauras VALUES
(1, 'Chủng loại\r\n'),
(2, 'Kiểu tay'),
(3, 'Kiểu thép tay'),
(4, 'Kiểu cổ'),
(5, 'Kiểu túi'),
(6, 'Kiểu nẹp'),
(7, 'Kiểu thân trước '),
(8, 'Kiểu Xẻ'),
(9, 'Kiểu thân sau'),
(10, 'Dài áo'),
(11, 'Dài tay'),
(12, 'Vòng ngực/Vòng mông'),
(13, 'Thành phần vải 1'),
(14, 'Khổ vải 1'),
(15, 'Thành phần vải 2'),
(16, 'Khổ vải 2'),
(17, 'Thành phần vải 3'),
(18, 'Khổ vải 3'),
(19, 'Số sản phẩm/sơ đồ\r\n'),
(20, 'Số lao động/ dây chuyền'),
(21, 'Mức Lương kỳ vọng của lao động'),
(22, 'Lợi nhuận dự kiến'),
(23, ' phụ phí'),
(24, 'Khoản phí khác');

-- 
-- Dumping data for table optionaos
--
-- Table da6.optionaos does not contain any data (it is empty)

-- 
-- Dumping data for table nguoidungs
--
INSERT INTO nguoidungs VALUES
('63CA8B37-2F08-402B-AA0C-B42D60112554', 'Nguyễn Văn Chiến', 'Admin', '123456', 'chien@gmail.com', '1234567890', 'Admin');

-- 
-- Dumping data for table loaivais
--
-- Table da6.loaivais does not contain any data (it is empty)

-- 
-- Dumping data for table loaitrangphucs
--
-- Table da6.loaitrangphucs does not contain any data (it is empty)

-- 
-- Dumping data for table loaidauras
--
INSERT INTO loaidauras VALUES
(1, 'Lỗi sản phẩm'),
(2, 'Định mức vải '),
(3, 'Định mức phụ liệu'),
(4, 'Xây dựng tiêu chuẩn kỹ thuật'),
(5, 'Tính giá gia công');

-- 
-- Dumping data for table kieuxes
--
INSERT INTO kieuxes VALUES
(1, 'Xẻ sườn', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Không xẻ sườn', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieutuitruocs
--
-- Table da6.kieutuitruocs does not contain any data (it is empty)

-- 
-- Dumping data for table kieutuisaus
--
-- Table da6.kieutuisaus does not contain any data (it is empty)

-- 
-- Dumping data for table kieutuis
--
INSERT INTO kieutuis VALUES
(1, 'Túi ốp không nắp', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Túi ốp có nắp', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'Túi bổ', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieutuigois
--
-- Table da6.kieutuigois does not contain any data (it is empty)

-- 
-- Dumping data for table kieuthantruocs
--
INSERT INTO kieuthantruocs VALUES
(1, 'Bổ ngang', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Bổ dọc', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'Bổ ngang và bổ dọc', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(4, 'Không bổ', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieuthansaus
--
INSERT INTO kieuthansaus VALUES
(1, 'Bổ ngang', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Bổ dọc', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'Bổ ngang và bổ dọc', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(4, 'Không bổ', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieutays
--
INSERT INTO kieutays VALUES
(1, 'Ngắn thường', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(2, 'Ngắn jaclan\r\n', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(3, 'Dài thường', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(4, 'Dài jaclan', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(5, 'Không tay', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00');

-- 
-- Dumping data for table kieuquans
--
-- Table da6.kieuquans does not contain any data (it is empty)

-- 
-- Dumping data for table kieuneps
--
INSERT INTO kieuneps VALUES
(1, 'Nẹp thường thuận', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Nẹp thường nghịch', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'Nẹp liền thuận', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(4, 'Nẹp liền nghịch', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(5, 'Nẹp hộp', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(6, 'Không nẹp', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieugaus
--
INSERT INTO kieugaus VALUES
(1, 'Bo', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(2, 'Thường', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00');

-- 
-- Dumping data for table kieucuatays
--
INSERT INTO kieucuatays VALUES
(1, 'Thường', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(2, 'Viền', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(3, 'Bo', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00');

-- 
-- Dumping data for table kieucuaquans
--
-- Table da6.kieucuaquans does not contain any data (it is empty)

-- 
-- Dumping data for table kieucos
--
INSERT INTO kieucos VALUES
(1, 'Cổ viền', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Cổ bo', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'Cổ có đáp', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(4, 'Cổ tàu', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(5, 'Cổ nam không chân(Bo)', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(6, 'Cổ nam không chân(vải chính)', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(7, 'Cổ nam có chân', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieucaps
--
-- Table da6.kieucaps does not contain any data (it is empty)

-- 
-- Dumping data for table jackets
--
-- Table da6.jackets does not contain any data (it is empty)

-- 
-- Dumping data for table files
--
INSERT INTO files VALUES
(1, 'TCKT-C_PS1.doc', 'D:\\DA6\\DA6.Solution\\DA6.Api\\Template\\TCKT-C_PS1.doc', '151552', NULL, NULL, NULL, '0001-01-01 00:00:00'),
(2, 'TCKT-M_PS1.doc', 'D:\\DA6\\DA6.Solution\\DA6.Api\\Template\\TCKT-M_PS1.doc', '668672', NULL, '2022-05-22 14:06:04.043069', NULL, '2022-05-22 14:06:04.043073'),
(3, 'TCKT-C_PS1.doc', 'D:\\DA6\\DA6.Solution\\DA6.Api\\Template\\TCKT-C_PS1.doc', '151552', NULL, '2022-05-22 23:13:10.546844', NULL, '2022-05-22 23:13:10.546875');

-- 
-- Dumping data for table dauras
--
INSERT INTO dauras VALUES
(1, 'Quy trình công nghệ'),
(2, 'Thời gian gia công 1 sản phẩm'),
(3, 'Năng suất'),
(4, 'Tỉ lệ lỗi (%)'),
(5, 'Các dạng lỗi'),
(6, 'Kiểu TK chuyền/ theo cụm'),
(7, 'Cữ/dưỡng sử dụng'),
(8, 'Định mức vải 1'),
(9, 'Định mức vải 2'),
(10, 'Định mức vải 3'),
(11, 'Định mức chỉ 1'),
(12, 'Định mức chỉ 2'),
(13, 'Định mức chỉ 3'),
(14, 'Định mức cúc 1'),
(15, 'Định mức cúc 2'),
(16, 'Định mức cúc 3'),
(17, 'Định mức mex/dựng 1'),
(18, 'Định mức mex/dựng 2'),
(19, 'Định mức mex/dựng 3'),
(20, 'Định mức Thiết bị '),
(21, 'TCKT cắt'),
(22, 'TCKT may'),
(23, 'TCKT hoàn thiện'),
(24, 'Giá CM basic'),
(25, 'Giá CM');

-- 
-- Dumping data for table daiquans
--
-- Table da6.daiquans does not contain any data (it is empty)

-- 
-- Dumping data for table chungloais
--
INSERT INTO chungloais VALUES
('PS_01', 'Polo Shirt 01', 'áo polo shirt ps01', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:26:53.091569', NULL, '2022-05-24 23:26:53.091571', 1),
('PS_02', 'Polo Shirt 02', 'áo polo shirt ps02', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:27:04.624299', NULL, '2022-05-24 23:27:04.624301', 1),
('PS_03', 'Polo Shirt 03', 'áo polo shirt ps03', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:27:12.578595', NULL, '2022-05-24 23:27:12.578597', 1),
('PS_04', 'Polo Shirt 04', 'áo polo shirt ps04', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:27:32.946993', NULL, '2022-05-24 23:27:32.946994', 1),
('PS_05', 'Polo Shirt 05', 'áo polo shirt ps05', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:28:00.108946', NULL, '2022-05-24 23:28:00.108947', 1),
('PS_06', 'Polo Shirt 06', 'áo polo shirt ps06', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:28:07.295149', NULL, '2022-05-24 23:28:07.29515', 1),
('PS_07', 'Polo Shirt 07', 'áo polo shirt ps07', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:28:14.528998', NULL, '2022-05-24 23:28:14.528999', 1),
('PS_08', 'Polo Shirt 08', 'áo polo shirt ps08', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:28:23.868069', NULL, '2022-05-24 23:28:23.86807', 1),
('PS_09', 'Polo Shirt 09', 'áo polo shirt ps09', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:28:33.189228', NULL, '2022-05-24 23:28:33.189235', 1),
('PS_10', 'Polo Shirt 10', 'áo polo shirt ps10', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:28:56.817325', NULL, '2022-05-24 23:28:56.817326', 1),
('PS_11', 'Polo Shirt 11', 'áo polo shirt ps11', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:29:17.169988', NULL, '2022-05-24 23:29:17.169989', 1),
('PS_12', 'Polo Shirt 12', 'áo polo shirt ps12', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:32:56.001466', NULL, '2022-05-24 23:32:56.001471', 1),
('PS_13', 'Polo Shirt 13', 'áo polo shirt ps13', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:42:49.532591', NULL, '2022-05-24 23:42:49.53259', 1),
('PS_14', 'Polo Shirt 14', 'áo polo shirt ps14', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:43:27.403184', NULL, '2022-05-24 23:43:27.403183', 1),
('PS_15', 'Polo Shirt 15', 'áo polo shirt ps15', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:43:36.378516', NULL, '2022-05-24 23:43:36.378509', 1),
('PS_16', 'Polo Shirt 16', 'áo polo shirt ps16', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:43:45.584293', NULL, '2022-05-24 23:43:45.584292', 1),
('PS_17', 'Polo Shirt 17', 'áo polo shirt ps17', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:43:52.663995', NULL, '2022-05-24 23:43:52.663994', 1),
('PS_18', 'Polo Shirt 18', 'áo polo shirt ps18', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:44:00.537185', NULL, '2022-05-24 23:44:00.537185', 1),
('PS_19', 'Polo Shirt 19', 'áo polo shirt ps19', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:44:08.897184', NULL, '2022-05-24 23:44:08.897183', 1),
('PS_20', 'Polo Shirt 20', 'áo polo shirt ps20', 'Áo', 'PShirt_01', NULL, '2022-05-24 23:44:19.365747', NULL, '2022-05-24 23:44:19.365746', 1),
('PShirt_01', 'Polo Shirt', 'áo polo shirt', 'Áo', NULL, NULL, '2022-05-24 23:26:00.178687', NULL, '2022-05-24 23:26:00.178703', 0),
('TS_01', 'T-Shirt 01', 'áo t-shirt ps01', 'Áo', 'TShirt_01', NULL, '2022-05-24 23:45:18.418007', NULL, '2022-05-24 23:45:18.418005', 1),
('TS_02', 'T-Shirt 02', 'áo t-shirt ps02', 'Áo', 'TShirt_01', NULL, '2022-05-24 23:45:28.254009', NULL, '2022-05-24 23:45:28.254009', 1),
('TS_03', 'T-Shirt 03', 'áo t-shirt ps03', 'Áo', 'TShirt_01', NULL, '2022-05-24 23:45:34.984254', NULL, '2022-05-24 23:45:34.984253', 1),
('TS_04', 'T-Shirt 04', 'áo t-shirt ps05', 'Áo', 'TShirt_01', NULL, '2022-05-24 23:45:42.634427', NULL, '2022-05-24 23:45:42.634426', 1),
('TS_06', 'T-Shirt 06', 'áo t-shirt ps06', 'Áo', 'TShirt_01', NULL, '2022-05-24 23:45:50.851555', NULL, '2022-05-24 23:45:50.851554', 1),
('TS_07', 'T-Shirt 07', 'áo t-shirt ps07', 'Áo', 'TShirt_01', NULL, '2022-05-24 23:45:58.052673', NULL, '2022-05-24 23:45:58.052673', 1),
('TS_08', 'T-Shirt 08', 'áo t-shirt ps08', 'Áo', 'TShirt_01', NULL, '2022-05-24 23:46:06.212502', NULL, '2022-05-24 23:46:06.212501', 1),
('TS_09', 'T-Shirt 09', 'áo t-shirt ps09', 'Áo', 'TShirt_01', NULL, '2022-05-24 23:46:14.810544', NULL, '2022-05-24 23:46:14.810544', 1),
('TS_10', 'T-Shirt 10', 'áo t-shirt ps10', 'Áo', 'TShirt_01', NULL, '2022-05-24 23:46:24.696491', NULL, '2022-05-24 23:46:24.69649', 1),
('TShirt_01', 'Áo', 'áo', 'Áo polo', '(null)', NULL, '2022-05-24 22:34:43.871455', NULL, '2022-05-24 22:44:27.91656', 0);

-- 
-- Dumping data for table aos
--
-- Table da6.aos does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;