--
-- Script was generated by Devart dbForge Studio 2020 for MySQL, Version 9.0.338.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 22/5/2022 2:25:40 PM
-- Server version: 8.0.27
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE da6;

--
-- Drop table `aos`
--
DROP TABLE IF EXISTS aos;

--
-- Drop table `chungloais`
--
DROP TABLE IF EXISTS chungloais;

--
-- Drop table `daiquans`
--
DROP TABLE IF EXISTS daiquans;

--
-- Drop table `files`
--
DROP TABLE IF EXISTS files;

--
-- Drop table `jackets`
--
DROP TABLE IF EXISTS jackets;

--
-- Drop table `kieucaps`
--
DROP TABLE IF EXISTS kieucaps;

--
-- Drop table `kieucos`
--
DROP TABLE IF EXISTS kieucos;

--
-- Drop table `kieucuaquans`
--
DROP TABLE IF EXISTS kieucuaquans;

--
-- Drop table `kieucuatays`
--
DROP TABLE IF EXISTS kieucuatays;

--
-- Drop table `kieugaus`
--
DROP TABLE IF EXISTS kieugaus;

--
-- Drop table `kieuneps`
--
DROP TABLE IF EXISTS kieuneps;

--
-- Drop table `kieuquans`
--
DROP TABLE IF EXISTS kieuquans;

--
-- Drop table `kieutays`
--
DROP TABLE IF EXISTS kieutays;

--
-- Drop table `kieuthansaus`
--
DROP TABLE IF EXISTS kieuthansaus;

--
-- Drop table `kieuthantruocs`
--
DROP TABLE IF EXISTS kieuthantruocs;

--
-- Drop table `kieutuigois`
--
DROP TABLE IF EXISTS kieutuigois;

--
-- Drop table `kieutuis`
--
DROP TABLE IF EXISTS kieutuis;

--
-- Drop table `kieutuisaus`
--
DROP TABLE IF EXISTS kieutuisaus;

--
-- Drop table `kieutuitruocs`
--
DROP TABLE IF EXISTS kieutuitruocs;

--
-- Drop table `kieuxes`
--
DROP TABLE IF EXISTS kieuxes;

--
-- Drop table `loaitrangphucs`
--
DROP TABLE IF EXISTS loaitrangphucs;

--
-- Drop table `loaivais`
--
DROP TABLE IF EXISTS loaivais;

--
-- Drop table `nguoidungs`
--
DROP TABLE IF EXISTS nguoidungs;

--
-- Drop table `quans`
--
DROP TABLE IF EXISTS quans;

--
-- Drop table `quytrinhchitiets`
--
DROP TABLE IF EXISTS quytrinhchitiets;

--
-- Drop table `quytrinhsanphams`
--
DROP TABLE IF EXISTS quytrinhsanphams;

--
-- Drop table `thanhphanvais`
--
DROP TABLE IF EXISTS thanhphanvais;

--
-- Drop table `vets`
--
DROP TABLE IF EXISTS vets;

--
-- Drop table `__efmigrationshistory`
--
DROP TABLE IF EXISTS __efmigrationshistory;

--
-- Set default database
--
USE da6;

--
-- Create table `__efmigrationshistory`
--
CREATE TABLE __efmigrationshistory (
  MigrationId varchar(150) NOT NULL,
  ProductVersion varchar(32) NOT NULL,
  PRIMARY KEY (MigrationId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `vets`
--
CREATE TABLE vets (
  MaVest varchar(255) NOT NULL,
  MaCL longtext NOT NULL,
  KieuNep longtext NOT NULL,
  KieuVe longtext NOT NULL,
  KieuCo longtext NOT NULL,
  KieuTuiNguc longtext NOT NULL,
  KieuTuiSuon longtext NOT NULL,
  KieuTay longtext NOT NULL,
  KieuThanTruoc longtext NOT NULL,
  KieuThanSau longtext NOT NULL,
  DaiAo float NOT NULL,
  VongGau float NOT NULL,
  VongNguc float NOT NULL,
  DaiTay float NOT NULL,
  ThanhPhanVai1 longtext NOT NULL,
  KhoVai1 float NOT NULL,
  ThanhPhanVai2 longtext NOT NULL,
  KhoVai2 float NOT NULL,
  ThanhPhanVai3 longtext NOT NULL,
  KhoVai3 float NOT NULL,
  ThanhPhanVaiLot1 longtext NOT NULL,
  KhoVaiLot1 float NOT NULL,
  ThanhPhanVaiLot2 longtext NOT NULL,
  KhoVaiLot2 float NOT NULL,
  ThanhPhanVaiLot3 longtext NOT NULL,
  KhoVaiLot3 float NOT NULL,
  SoSanPhanTrenSoDo int NOT NULL,
  SoLaoDongTrenDayTruyen int NOT NULL,
  MucLuongKyVong float NOT NULL,
  LoiNhuanDuKien float NOT NULL,
  PhuPhi float NOT NULL,
  KhoanPhiKhac float NOT NULL,
  PRIMARY KEY (MaVest)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `thanhphanvais`
--
CREATE TABLE thanhphanvais (
  MaThanhPhanVai int NOT NULL AUTO_INCREMENT,
  TenThanhPhanVai longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaThanhPhanVai)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `quytrinhsanphams`
--
CREATE TABLE quytrinhsanphams (
  MaQuyTrinhSanPham varchar(255) NOT NULL,
  STT int NOT NULL,
  MaSanPham longtext NOT NULL,
  TenQuyTrinh longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaQuyTrinhSanPham)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `quytrinhchitiets`
--
CREATE TABLE quytrinhchitiets (
  MaQuyTrinhChiTiet varchar(255) NOT NULL,
  STT int NOT NULL,
  NoiDungBuoc longtext NOT NULL,
  ThietBi longtext NOT NULL,
  BacTho longtext NOT NULL,
  ThoiGianCheTao int NOT NULL,
  DonGia float NOT NULL,
  GhiChu longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaQuyTrinhChiTiet)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `quans`
--
CREATE TABLE quans (
  MaQuan varchar(255) NOT NULL,
  MaCL longtext NOT NULL,
  KieuQuan longtext NOT NULL,
  KieuCap longtext NOT NULL,
  KieuTuiTruoc longtext NOT NULL,
  KieuTuiSau longtext NOT NULL,
  KieuTuiGoi longtext NOT NULL,
  KieuCuaQuan longtext NOT NULL,
  KieuThanTruoc longtext NOT NULL,
  KieuThanSau longtext NOT NULL,
  DaiQuan longtext NOT NULL,
  VongMong float NOT NULL,
  VongBung float NOT NULL,
  ThanhPhanVai1 longtext NOT NULL,
  KhoVai1 float NOT NULL,
  ThanhPhanVai2 longtext NOT NULL,
  KhoVai2 float NOT NULL,
  ThanhPhanVai3 longtext NOT NULL,
  KhoVai3 float NOT NULL,
  ThanhPhanVaiLot1 longtext NOT NULL,
  KhoVaiLot1 float NOT NULL,
  ThanhPhanVaiLot2 longtext NOT NULL,
  KhoVaiLot2 float NOT NULL,
  ThanhPhanVaiLot3 longtext NOT NULL,
  KhoVaiLot3 float NOT NULL,
  SoSanPhanTrenSoDo int NOT NULL,
  SoLaoDongTrenDayTruyen int NOT NULL,
  MucLuongKyVong float NOT NULL,
  LoiNhuanDuKien float NOT NULL,
  PhuPhi float NOT NULL,
  KhoanPhiKhac float NOT NULL,
  PRIMARY KEY (MaQuan)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `nguoidungs`
--
CREATE TABLE nguoidungs (
  NguoiDungId char(36) CHARACTER SET ascii COLLATE ascii_general_ci NOT NULL,
  TenNguoiDung longtext NOT NULL,
  TaiKhoan longtext NOT NULL,
  MatKhau longtext NOT NULL,
  Email longtext NOT NULL,
  SoDienThoai longtext NOT NULL,
  Quyen longtext NOT NULL,
  PRIMARY KEY (NguoiDungId)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 16384,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `loaivais`
--
CREATE TABLE loaivais (
  MaVai varchar(255) NOT NULL,
  TenVai longtext DEFAULT NULL,
  ThanhPhan longtext NOT NULL,
  ChucNang longtext NOT NULL,
  MoTa longtext NOT NULL,
  PRIMARY KEY (MaVai)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `loaitrangphucs`
--
CREATE TABLE loaitrangphucs (
  MaTP varchar(255) NOT NULL,
  Ten varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  MoTa varchar(100) CHARACTER SET utf8 COLLATE utf8_general_ci DEFAULT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaTP)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieuxes`
--
CREATE TABLE kieuxes (
  MaKieuXe int NOT NULL AUTO_INCREMENT,
  TenKieuXe longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuXe)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieutuitruocs`
--
CREATE TABLE kieutuitruocs (
  MaKieuTuiTruoc int NOT NULL AUTO_INCREMENT,
  TenKieuTuiTruoc longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuTuiTruoc)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieutuisaus`
--
CREATE TABLE kieutuisaus (
  MaKieuTuiSau int NOT NULL AUTO_INCREMENT,
  TenKieuTuiSau longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuTuiSau)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieutuis`
--
CREATE TABLE kieutuis (
  MaKieuTui int NOT NULL AUTO_INCREMENT,
  TenKieuTui longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuTui)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieutuigois`
--
CREATE TABLE kieutuigois (
  MaKieuTuiGoi int NOT NULL AUTO_INCREMENT,
  TenKieuTuiGoi longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuTuiGoi)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieuthantruocs`
--
CREATE TABLE kieuthantruocs (
  MaKieuThanTruoc int NOT NULL AUTO_INCREMENT,
  TenKieuThanTruoc longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuThanTruoc)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieuthansaus`
--
CREATE TABLE kieuthansaus (
  MaKieuThanSau int NOT NULL AUTO_INCREMENT,
  TenKieuThanSau longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuThanSau)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieutays`
--
CREATE TABLE kieutays (
  MaKieuTay int NOT NULL AUTO_INCREMENT,
  TenKieu longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuTay)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 3276,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieuquans`
--
CREATE TABLE kieuquans (
  MaKieuQuan int NOT NULL AUTO_INCREMENT,
  TenKieuQuan longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuQuan)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieuneps`
--
CREATE TABLE kieuneps (
  MaKieuNep int NOT NULL AUTO_INCREMENT,
  TenKieuNep longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuNep)
)
ENGINE = INNODB,
AUTO_INCREMENT = 7,
AVG_ROW_LENGTH = 2730,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieugaus`
--
CREATE TABLE kieugaus (
  MaKieuGau int NOT NULL AUTO_INCREMENT,
  TenKieuGau longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuGau)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieucuatays`
--
CREATE TABLE kieucuatays (
  MaKieuCuaTay int NOT NULL AUTO_INCREMENT,
  TenKieuCuaTay longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuCuaTay)
)
ENGINE = INNODB,
AUTO_INCREMENT = 4,
AVG_ROW_LENGTH = 5461,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieucuaquans`
--
CREATE TABLE kieucuaquans (
  MaKieuCuaQuan int NOT NULL AUTO_INCREMENT,
  TenKieuCuaQuan longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuCuaQuan)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieucos`
--
CREATE TABLE kieucos (
  MaKieuCo int NOT NULL AUTO_INCREMENT,
  TenKieuCo longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuCo)
)
ENGINE = INNODB,
AUTO_INCREMENT = 8,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `kieucaps`
--
CREATE TABLE kieucaps (
  MaKieuCap int NOT NULL AUTO_INCREMENT,
  TenKieuCap longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaKieuCap)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `jackets`
--
CREATE TABLE jackets (
  MaJket varchar(255) NOT NULL,
  MaCL longtext NOT NULL,
  Ruot longtext NOT NULL,
  KieuChan longtext NOT NULL,
  KieuGau longtext NOT NULL,
  KieuMu longtext NOT NULL,
  KieuCo longtext NOT NULL,
  KieuTuiNguc longtext NOT NULL,
  KieuTuiSuon longtext NOT NULL,
  KieuKhoaNep longtext NOT NULL,
  KieuTay longtext NOT NULL,
  KieuThanTruoc longtext NOT NULL,
  DaiAo float NOT NULL,
  VongNguc float NOT NULL,
  DaiTay float NOT NULL,
  ThanhPhanVaiChinh1 longtext NOT NULL,
  KhoVaiChinh1 float NOT NULL,
  ThanhPhanVaiChinh2 longtext NOT NULL,
  KhoVaiChinh2 float NOT NULL,
  ThanhPhanVaiChinh3 longtext NOT NULL,
  KhoVaiChinh3 float NOT NULL,
  ThanhPhanVaiLot1 longtext NOT NULL,
  KhoVaiLot1 float NOT NULL,
  ThanhPhanVaiLot2 longtext NOT NULL,
  KhoVaiLot2 float NOT NULL,
  ThanhPhanVaiLot3 longtext NOT NULL,
  KhoVaiLot3 float NOT NULL,
  SoSanPhanTrenSoDo int NOT NULL,
  SoLaoDongTrenDayTruyen int NOT NULL,
  MucLuongKyVong float NOT NULL,
  LoiNhuanDuKien float NOT NULL,
  PhuPhi float NOT NULL,
  KhoanPhiKhac float NOT NULL,
  PRIMARY KEY (MaJket)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `files`
--
CREATE TABLE files (
  MaFile int NOT NULL AUTO_INCREMENT,
  TenFile longtext NOT NULL,
  Path longtext NOT NULL,
  Size longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL DEFAULT '0001-01-01 00:00:00.000000',
  PRIMARY KEY (MaFile)
)
ENGINE = INNODB,
AUTO_INCREMENT = 3,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `daiquans`
--
CREATE TABLE daiquans (
  MaDaiQuan int NOT NULL AUTO_INCREMENT,
  TenDaiQuan longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaDaiQuan)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `chungloais`
--
CREATE TABLE chungloais (
  MaCL varchar(255) NOT NULL,
  Ten longtext DEFAULT NULL,
  MoTa longtext DEFAULT NULL,
  Kieu longtext NOT NULL,
  ParenId longtext NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaCL)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create table `aos`
--
CREATE TABLE aos (
  MaA varchar(255) NOT NULL,
  MaCL longtext NOT NULL,
  KieuTay longtext NOT NULL,
  KieuCuaTay longtext NOT NULL,
  KieuGau longtext NOT NULL,
  KieuCo longtext NOT NULL,
  KieuTui longtext NOT NULL,
  KieuNep longtext NOT NULL,
  KieuThanTruoc longtext NOT NULL,
  KieuXe longtext NOT NULL,
  KieuThanSau longtext NOT NULL,
  DaiAo float NOT NULL,
  DaiTay float NOT NULL,
  VongNguc float NOT NULL,
  VongMong float NOT NULL,
  ThanhPhanVai1 longtext NOT NULL,
  TrongLuongVai1 float NOT NULL,
  KhoVai1 float NOT NULL,
  ThanhPhanVai2 longtext NOT NULL,
  TrongLuongVai2 float NOT NULL,
  KhoVai2 float NOT NULL,
  ThanhPhanVai3 longtext NOT NULL,
  TrongLuongVai3 float NOT NULL,
  KhoVai3 float NOT NULL,
  SoSanPhanTrenSoDo int NOT NULL,
  SoLaoDongTrenDayTruyen int NOT NULL,
  MucLuongKyVong float NOT NULL,
  LoiNhuanDuKien float NOT NULL,
  PhuPhi float NOT NULL,
  KhoanPhiKhac float NOT NULL,
  CreatedBy longtext DEFAULT NULL,
  CreatedDate datetime(6) DEFAULT NULL,
  ModifiedBy longtext DEFAULT NULL,
  ModifiedDate datetime(6) NOT NULL,
  PRIMARY KEY (MaA)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

-- 
-- Dumping data for table __efmigrationshistory
--
INSERT INTO __efmigrationshistory VALUES
('20220521102804_initial', '6.0.4'),
('20220522033611_AddFile', '6.0.4'),
('20220522043935_addbaseClassfile', '6.0.4'),
('20220522072212_updatetableNguoidung', '6.0.4');

-- 
-- Dumping data for table vets
--
-- Table da6.vets does not contain any data (it is empty)

-- 
-- Dumping data for table thanhphanvais
--
INSERT INTO thanhphanvais VALUES
(1, 'bông 100%', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'TC 65-35', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'TC 35-65', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(4, 'PES 100%', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(5, 'Ryon', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(6, 'Bambo', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table quytrinhsanphams
--
-- Table da6.quytrinhsanphams does not contain any data (it is empty)

-- 
-- Dumping data for table quytrinhchitiets
--
-- Table da6.quytrinhchitiets does not contain any data (it is empty)

-- 
-- Dumping data for table quans
--
-- Table da6.quans does not contain any data (it is empty)

-- 
-- Dumping data for table nguoidungs
--
INSERT INTO nguoidungs VALUES
('63CA8B37-2F08-402B-AA0C-B42D60112554', 'Nguyễn Văn Chiến', 'Admin', '123456', 'chien@gmail.com', '1234567890', 'Admin');

-- 
-- Dumping data for table loaivais
--
-- Table da6.loaivais does not contain any data (it is empty)

-- 
-- Dumping data for table loaitrangphucs
--
-- Table da6.loaitrangphucs does not contain any data (it is empty)

-- 
-- Dumping data for table kieuxes
--
INSERT INTO kieuxes VALUES
(1, 'Xẻ sườn', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Không xẻ sườn', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieutuitruocs
--
-- Table da6.kieutuitruocs does not contain any data (it is empty)

-- 
-- Dumping data for table kieutuisaus
--
-- Table da6.kieutuisaus does not contain any data (it is empty)

-- 
-- Dumping data for table kieutuis
--
INSERT INTO kieutuis VALUES
(1, 'Túi ốp không nắp', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Túi ốp có nắp', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'Túi bổ', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieutuigois
--
-- Table da6.kieutuigois does not contain any data (it is empty)

-- 
-- Dumping data for table kieuthantruocs
--
INSERT INTO kieuthantruocs VALUES
(1, 'Bổ ngang', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Bổ dọc', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'Bổ ngang và bổ dọc', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(4, 'Không bổ', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieuthansaus
--
INSERT INTO kieuthansaus VALUES
(1, 'Bổ ngang', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Bổ dọc', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'Bổ ngang và bổ dọc', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(4, 'Không bổ', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieutays
--
INSERT INTO kieutays VALUES
(1, 'Ngắn thường', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(2, 'Ngắn jaclan\r\n', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(3, 'Dài thường', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(4, 'Dài jaclan', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(5, 'Không tay', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00');

-- 
-- Dumping data for table kieuquans
--
-- Table da6.kieuquans does not contain any data (it is empty)

-- 
-- Dumping data for table kieuneps
--
INSERT INTO kieuneps VALUES
(1, 'Nẹp thường thuận', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Nẹp thường nghịch', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'Nẹp liền thuận', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(4, 'Nẹp liền nghịch', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(5, 'Nẹp hộp', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(6, 'Không nẹp', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieugaus
--
INSERT INTO kieugaus VALUES
(1, 'Bo', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(2, 'Thường', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00');

-- 
-- Dumping data for table kieucuatays
--
INSERT INTO kieucuatays VALUES
(1, 'Thường', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(2, 'Viền', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00'),
(3, 'Bo', NULL, '2022-05-14 00:00:00', NULL, '2022-05-14 00:00:00');

-- 
-- Dumping data for table kieucuaquans
--
-- Table da6.kieucuaquans does not contain any data (it is empty)

-- 
-- Dumping data for table kieucos
--
INSERT INTO kieucos VALUES
(1, 'Cổ viền', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(2, 'Cổ bo', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(3, 'Cổ có đáp', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(4, 'Cổ tàu', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(5, 'Cổ nam không chân(Bo)', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(6, 'Cổ nam không chân(vải chính)', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00'),
(7, 'Cổ nam có chân', NULL, '2022-05-15 00:00:00', NULL, '2022-05-15 00:00:00');

-- 
-- Dumping data for table kieucaps
--
-- Table da6.kieucaps does not contain any data (it is empty)

-- 
-- Dumping data for table jackets
--
-- Table da6.jackets does not contain any data (it is empty)

-- 
-- Dumping data for table files
--
INSERT INTO files VALUES
(1, 'TCKT-C_PS1.doc', 'D:\\DA6\\DA6.Solution\\DA6.Api\\Template\\TCKT-C_PS1.doc', '151552', NULL, NULL, NULL, '0001-01-01 00:00:00'),
(2, 'TCKT-M_PS1.doc', 'D:\\DA6\\DA6.Solution\\DA6.Api\\Template\\TCKT-M_PS1.doc', '668672', NULL, '2022-05-22 14:06:04.043069', NULL, '2022-05-22 14:06:04.043073');

-- 
-- Dumping data for table daiquans
--
-- Table da6.daiquans does not contain any data (it is empty)

-- 
-- Dumping data for table chungloais
--
-- Table da6.chungloais does not contain any data (it is empty)

-- 
-- Dumping data for table aos
--
-- Table da6.aos does not contain any data (it is empty)

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;