// <auto-generated />
using System;
using DA6.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DA6.Api.Migrations
{
    [DbContext(typeof(DA6DbContext))]
    partial class DA6DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DA6.Api.Entities.JacKet", b =>
                {
                    b.Property<Guid>("MaJket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChungLoaiMaCL")
                        .HasColumnType("char(36)");

                    b.Property<float>("DaiAo")
                        .HasColumnType("float");

                    b.Property<float>("DaiTay")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiChinh1")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiChinh2")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiChinh3")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiLot1")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiLot2")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiLot3")
                        .HasColumnType("float");

                    b.Property<float>("KhoanPhiKhac")
                        .HasColumnType("float");

                    b.Property<string>("KieuChan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuCo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuGau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuKhoaNep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuMu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuTay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuThanTruoc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuTuiNguc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuTuiSuon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("LoiNhuanDuKien")
                        .HasColumnType("float");

                    b.Property<Guid>("MaCL")
                        .HasColumnType("char(36)");

                    b.Property<float>("MucLuongKyVong")
                        .HasColumnType("float");

                    b.Property<float>("PhuPhi")
                        .HasColumnType("float");

                    b.Property<string>("Ruot")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SoLaoDongTrenDayTruyen")
                        .HasColumnType("int");

                    b.Property<int>("SoSanPhanTrenSoDo")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVaiChinh1")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVaiChinh2")
                        .HasColumnType("int");

                    b.Property<string>("ThanhPhanVaiChinh3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ThanhPhanVaiLot1")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVaiLot2")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVaiLot3")
                        .HasColumnType("int");

                    b.Property<float>("VongNguc")
                        .HasColumnType("float");

                    b.HasKey("MaJket");

                    b.HasIndex("ChungLoaiMaCL");

                    b.ToTable("JacKets");
                });

            modelBuilder.Entity("DA6.Api.Entities.LoaiVai", b =>
                {
                    b.Property<Guid>("MaVai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ChucNang")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenVai")
                        .HasColumnType("longtext");

                    b.Property<string>("ThanhPhan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaVai");

                    b.ToTable("LoaiVais");
                });

            modelBuilder.Entity("DA6.Api.Entities.Quan", b =>
                {
                    b.Property<Guid>("MaQuan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChungLoaiMaCL")
                        .HasColumnType("char(36)");

                    b.Property<string>("DaiQuan")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("KhoVai1")
                        .HasColumnType("float");

                    b.Property<float>("KhoVai2")
                        .HasColumnType("float");

                    b.Property<float>("KhoVai3")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiLot1")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiLot2")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiLot3")
                        .HasColumnType("float");

                    b.Property<float>("KhoanPhiKhac")
                        .HasColumnType("float");

                    b.Property<int>("KieuCap")
                        .HasColumnType("int");

                    b.Property<int>("KieuCuaQuan")
                        .HasColumnType("int");

                    b.Property<int>("KieuQuan")
                        .HasColumnType("int");

                    b.Property<string>("KieuThanSau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuThanTruoc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("KieuTuiGoi")
                        .HasColumnType("int");

                    b.Property<int>("KieuTuiSau")
                        .HasColumnType("int");

                    b.Property<int>("KieuTuiTruoc")
                        .HasColumnType("int");

                    b.Property<float>("LoiNhuanDuKien")
                        .HasColumnType("float");

                    b.Property<Guid>("MaCL")
                        .HasColumnType("char(36)");

                    b.Property<float>("MucLuongKyVong")
                        .HasColumnType("float");

                    b.Property<float>("PhuPhi")
                        .HasColumnType("float");

                    b.Property<int>("SoLaoDongTrenDayTruyen")
                        .HasColumnType("int");

                    b.Property<int>("SoSanPhanTrenSoDo")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVai1")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVai2")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVai3")
                        .HasColumnType("int");

                    b.Property<string>("ThanhPhanVaiLot1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThanhPhanVaiLot2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThanhPhanVaiLot3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("VongBung")
                        .HasColumnType("float");

                    b.Property<float>("VongMong")
                        .HasColumnType("float");

                    b.HasKey("MaQuan");

                    b.HasIndex("ChungLoaiMaCL");

                    b.ToTable("Quans");
                });

            modelBuilder.Entity("DA6.Api.Entities.QuyTrinhChiTiet", b =>
                {
                    b.Property<Guid>("MaQuyTrinhChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BacTho")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("DonGia")
                        .HasColumnType("float");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NoiDungBuoc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<string>("ThietBi")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ThoiGianCheTao")
                        .HasColumnType("int");

                    b.HasKey("MaQuyTrinhChiTiet");

                    b.ToTable("QuyTrinhChiTiets");
                });

            modelBuilder.Entity("DA6.Api.Entities.QuyTrinhSanPham", b =>
                {
                    b.Property<Guid>("MaQuyTrinhSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("MaSanPham")
                        .HasColumnType("char(36)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("STT")
                        .HasColumnType("int");

                    b.Property<string>("TenQuyTrinh")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("MaQuyTrinhSanPham");

                    b.ToTable("QuyTrinhSanPhams");
                });

            modelBuilder.Entity("DA6.Api.Entities.Vest", b =>
                {
                    b.Property<Guid>("MaVest")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChungLoaiMaCL")
                        .HasColumnType("char(36)");

                    b.Property<float>("DaiAo")
                        .HasColumnType("float");

                    b.Property<float>("DaiTay")
                        .HasColumnType("float");

                    b.Property<float>("KhoVai1")
                        .HasColumnType("float");

                    b.Property<float>("KhoVai2")
                        .HasColumnType("float");

                    b.Property<float>("KhoVai3")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiLot1")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiLot2")
                        .HasColumnType("float");

                    b.Property<float>("KhoVaiLot3")
                        .HasColumnType("float");

                    b.Property<float>("KhoanPhiKhac")
                        .HasColumnType("float");

                    b.Property<string>("KieuCo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuNep")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuTay")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuThanSau")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuThanTruoc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuTuiNguc")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuTuiSuon")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("KieuVe")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("LoiNhuanDuKien")
                        .HasColumnType("float");

                    b.Property<Guid>("MaCL")
                        .HasColumnType("char(36)");

                    b.Property<float>("MucLuongKyVong")
                        .HasColumnType("float");

                    b.Property<float>("PhuPhi")
                        .HasColumnType("float");

                    b.Property<int>("SoLaoDongTrenDayTruyen")
                        .HasColumnType("int");

                    b.Property<int>("SoSanPhanTrenSoDo")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVai1")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVai2")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVai3")
                        .HasColumnType("int");

                    b.Property<string>("ThanhPhanVaiLot1")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThanhPhanVaiLot2")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ThanhPhanVaiLot3")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("VongGau")
                        .HasColumnType("float");

                    b.Property<float>("VongNguc")
                        .HasColumnType("float");

                    b.HasKey("MaVest");

                    b.HasIndex("ChungLoaiMaCL");

                    b.ToTable("Vests");
                });

            modelBuilder.Entity("DA6.Core.Entities.Ao", b =>
                {
                    b.Property<Guid>("MaA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ChungLoaiMaCL")
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("DaiAo")
                        .HasColumnType("float");

                    b.Property<float>("DaiTay")
                        .HasColumnType("float");

                    b.Property<float>("KhoVai1")
                        .HasColumnType("float");

                    b.Property<float>("KhoVai2")
                        .HasColumnType("float");

                    b.Property<float>("KhoVai3")
                        .HasColumnType("float");

                    b.Property<float>("KhoanPhiKhac")
                        .HasColumnType("float");

                    b.Property<int>("KieuCo")
                        .HasColumnType("int");

                    b.Property<int>("KieuCuaTay")
                        .HasColumnType("int");

                    b.Property<int>("KieuGau")
                        .HasColumnType("int");

                    b.Property<int>("KieuNep")
                        .HasColumnType("int");

                    b.Property<int>("KieuTay")
                        .HasColumnType("int");

                    b.Property<int>("KieuThanSau")
                        .HasColumnType("int");

                    b.Property<int>("KieuThanTruoc")
                        .HasColumnType("int");

                    b.Property<int>("KieuTui")
                        .HasColumnType("int");

                    b.Property<int>("KieuXe")
                        .HasColumnType("int");

                    b.Property<float>("LoiNhuanDuKien")
                        .HasColumnType("float");

                    b.Property<Guid>("MaCL")
                        .HasColumnType("char(36)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<float>("MucLuongKyVong")
                        .HasColumnType("float");

                    b.Property<float>("PhuPhi")
                        .HasColumnType("float");

                    b.Property<int>("SoLaoDongTrenDayTruyen")
                        .HasColumnType("int");

                    b.Property<int>("SoSanPhanTrenSoDo")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVai1")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVai2")
                        .HasColumnType("int");

                    b.Property<int>("ThanhPhanVai3")
                        .HasColumnType("int");

                    b.Property<float>("TrongLuongVai1")
                        .HasColumnType("float");

                    b.Property<float>("TrongLuongVai2")
                        .HasColumnType("float");

                    b.Property<float>("TrongLuongVai3")
                        .HasColumnType("float");

                    b.Property<float>("VongMong")
                        .HasColumnType("float");

                    b.Property<float>("VongNguc")
                        .HasColumnType("float");

                    b.HasKey("MaA");

                    b.HasIndex("ChungLoaiMaCL");

                    b.ToTable("Ao");
                });

            modelBuilder.Entity("DA6.Core.Entities.ChungLoai", b =>
                {
                    b.Property<Guid>("MaCL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kieu")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MoTa")
                        .HasColumnType("longtext");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ten")
                        .HasColumnType("longtext");

                    b.HasKey("MaCL");

                    b.ToTable("ChungLoai");
                });

            modelBuilder.Entity("DA6.Core.Entities.LoaiTrangPhuc", b =>
                {
                    b.Property<Guid>("MaTP")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MoTa")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Ten")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("MaTP");

                    b.ToTable("LoaiTrangPhuc");
                });

            modelBuilder.Entity("DA6.Api.Entities.JacKet", b =>
                {
                    b.HasOne("DA6.Core.Entities.ChungLoai", "ChungLoai")
                        .WithMany("JacKets")
                        .HasForeignKey("ChungLoaiMaCL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChungLoai");
                });

            modelBuilder.Entity("DA6.Api.Entities.Quan", b =>
                {
                    b.HasOne("DA6.Core.Entities.ChungLoai", "ChungLoai")
                        .WithMany("Quans")
                        .HasForeignKey("ChungLoaiMaCL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChungLoai");
                });

            modelBuilder.Entity("DA6.Api.Entities.Vest", b =>
                {
                    b.HasOne("DA6.Core.Entities.ChungLoai", "ChungLoai")
                        .WithMany("Vests")
                        .HasForeignKey("ChungLoaiMaCL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChungLoai");
                });

            modelBuilder.Entity("DA6.Core.Entities.Ao", b =>
                {
                    b.HasOne("DA6.Core.Entities.ChungLoai", "ChungLoai")
                        .WithMany("Aos")
                        .HasForeignKey("ChungLoaiMaCL")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChungLoai");
                });

            modelBuilder.Entity("DA6.Core.Entities.ChungLoai", b =>
                {
                    b.Navigation("Aos");

                    b.Navigation("JacKets");

                    b.Navigation("Quans");

                    b.Navigation("Vests");
                });
#pragma warning restore 612, 618
        }
    }
}
